#!/usr/bin/env bash
#ping uses ICMP to make sure that a network device remains online or to troubleshoot issues 
if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
